<?php

namespace AppBundle\Entity;
namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
	public function findByIdUser($id){
		$qb = $this->createQueryBuilder('p');

		$qb->select('p.id, p.url, p.idUser, p.pos')
		   ->where('p.pos != :null')
		   ->andWhere('p.idUser = :id')
		   ->orderby('p.pos', 'asc')
		   ->setParameters(array('id' => $id, 'null' => "null"));


        return $qb->getQuery()->getResult();
    }

    public function findByIdUserNULL($id){
		$qb = $this->createQueryBuilder('p');

		$qb->select('p.id, p.url, p.idUser, p.pos')
		   ->where('p.idUser = :id')
		   ->orderby('p.pos', 'asc')
		   ->setParameters(array('id' => $id));


        return $qb->getQuery()->getResult();
    }

    public function findByIdUserReal($id){
		$qb = $this->createQueryBuilder('p');

		$qb->select('p.id')
		   ->where('p.idUser = :id')
		   ->setParameters(array('id' => $id));


        return $qb->getQuery()->getResult();
    }

    public function findAllIdAffichable(){
		$qb = $this->createQueryBuilder('p');

		$qb->select('p.idUser')
		   ->where('p.pos != :null')
		   ->distinct()
		   ->setParameters(array('null' => "null"));


        return $qb->getQuery()->getArrayResult();
    }
}
