<?php

namespace AppBundle\Entity;
namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
	public function findByIdUser($id){
		$qb = $this->createQueryBuilder('p');

		$qb->select('p.url, p.idUser')
		   ->where('p.pos != :null')
		   ->andWhere('p.idUser = :id')
		   ->orderby('p.pos', 'asc')
		   ->setParameters(array('id' => $id, 'null' => "null"));


        return $qb->getQuery()->getResult();
    }
}
